### ISSUE TITLE
🏁 Tiled Map Editor ↔ v21.0.4 (Tiled.exe requires elevated account)

### ISSUE THREAD

**Issue by Archeia** [itchio/itch-compatibility-watchlist#385]
:rotating_light: tool [Tiled Map Editor](https://thorbjorn.itch.io/tiled) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/34ba691a541836d1fb323a2e72eaaecc).

:running: I just clicked launch and it does not want to :<

**Comment by fasterthanlime** [comment]
Hey, if you open `C:\Users\Regius\AppData\Roaming\itch\apps\Tiled Map Editor\` in windows' file explorer, is there a tiled.exe there? How does it look? (what's its size, is there a little shield in the corner of its icon, etc. — a screenshot of the file explorer in 'Detailed' listing would be great!)

And what happens when you double-click on it from the explorer?

*Hint: you can open that location by clicking the 'Show local files' button from within the app (bottom-right when Tiled is open as a tab)*

**Comment by Archeia** [comment]
Hello~
I don't think tiled itself is broken since I can use it. But just using itch client and opening it doesn't seem to work;;

But I wanted to mention a step by step just in case!
The moment I open Itch this happens.
![image](https://cloud.githubusercontent.com/assets/6222499/20866503/5b1e7fbe-ba69-11e6-920b-b8c69ff492f2.png)

I figured it's just a network error and I ignored it.
When I open Tiled here's what happens:
![image](https://cloud.githubusercontent.com/assets/6222499/20866514/70776c54-ba69-11e6-886d-410108efaa75.png)

When I checked the folder here's what I have.
![image](https://cloud.githubusercontent.com/assets/6222499/20866517/93e569fc-ba69-11e6-8bb9-fe7a03ca0252.png)

**Comment by fasterthanlime** [comment]
@Archeia thanks for the step-by-step! The first error has nothing to do with it, although I'm curious if you can open https://nuts.itch.zone/notes in your regular web browser (that's the update server).

@bjorn is it normal for recent Tiled releases to require administrator privileges to run? Does WinSparkle require that?

**Comment by Archeia** [comment]
@fasterthanlime I can open that website no problem :D

**Comment by bjorn** [comment]
> @bjorn is it normal for recent Tiled releases to require administrator privileges to run? Does WinSparkle require that?

Erm, it shouldn't and I have no idea how that shield icon ended up on the tiled.exe. I haven't seen this before. I'll have a look myself.

@Archeia Did this happen since upgrading from 0.17.1 to 0.17.2?

**Comment by Archeia** [comment]
@bjorn I think so or at the very least, I just installed a new version (since I reformatted my pc) and just went to work. It was working OK until I restarted my pc I think? I did pin it to my taskbar in case I get lazy to open itch I wonder if that's connected to anything.

Oh, after checking your replies and removing the admin tag on the exe it works perfectly fine. That is interesting! I-I guess my issue is solved ;v;

**Comment by fasterthanlime** [comment]
> Oh, after checking your replies and removing the admin tag on the exe it works perfectly fine.

:o how did you manage to do that? Uncheck "Run as administrator" in the file's properties?

**Comment by bjorn** [comment]
> I-I guess my issue is solved ;v;

I don't think it's solved until we found out how the admin tag got there in the first place.

**Comment by bjorn** [comment]
I've just installed Tiled 0.17.2 64-bit through the itch app but the `tiled.exe` did not get the admin tag. You didn't by any chance add this yourself, @Archeia?
